In [ ]:
import pandas as pd, numpy as np

path = '/home/eltito/repositorios/Curso-NumPy-Pandas-Matplotlib/Online_Retail.csv'
retail_data = pd.read_csv(path, encoding='latin1')

In [ ]:
# iloc[0] toma los valores de la primer fila

first_row = retail_data.iloc[0]
first_row

InvoiceNo                                  536365
StockCode                                  85123A
Description    WHITE HANGING HEART T-LIGHT HOLDER
Quantity                                        6
InvoiceDate                          12/1/10 8:26
UnitPrice                                    2.55
CustomerID                                17850.0
Country                            United Kingdom
Name: 0, dtype: object

In [ ]:
# Toma los valores de la fila 6 hasta la 8 (no inclusive)

first_five_rows = retail_data.iloc[6:8]
first_five_rows

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
6,536365,21730,GLASS STAR FROSTED T-LIGHT HOLDER,6,12/1/10 8:26,4.25,17850.0,United Kingdom
7,536366,22633,HAND WARMER UNION JACK,6,12/1/10 8:28,1.85,17850.0,United Kingdom

In [6]:
# Tambien podemos definir la columna
# De la fila 1 a la 3, de la columna 1 a la 2

subset = retail_data.iloc[:3, :2]
subset

  InvoiceNo StockCode
0    536365    85123A
1    536365     71053
2    536365    84406B

In [8]:
# Aca busco un una posición en especifico, fila 1 columna 2

retail_value = retail_data.iloc[1, 2]
retail_value

'WHITE METAL LANTERN'

In [10]:
quantity_columns = retail_data.loc[:, 'Quantity']
quantity_columns

0          6
1          6
2          8
3          6
4          6
          ..
541904    12
541905     6
541906     4
541907     4
541908     3
Name: Quantity, Length: 541909, dtype: int64

In [12]:
quantity_unitprices_column = retail_data.loc[:,['Quantity','UnitPrice']]
quantity_unitprices_column

        Quantity  UnitPrice
0              6       2.55
1              6       3.39
2              8       2.75
3              6       3.39
4              6       3.39
...          ...        ...
541904        12       0.85
541905         6       2.10
541906         4       4.15
541907         4       4.15
541908         3       4.95

[541909 rows x 2 columns]