In [1]:
import pandas as pd, numpy as np

path = '/home/eltito/repositorios/Curso-NumPy-Pandas-Matplotlib/Online_Retail.csv'
retail_data = pd.read_csv(path, encoding='latin1')

In [3]:
# Busqueda de datos faltantes

missing_data = retail_data.isna()
missing_data

missing_data_count = retail_data.isna().sum()
missing_data_count

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [4]:
# Puedo eliminar las filas con datos faltantes

no_missing_rows = retail_data.dropna()
no_missing_rows

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/11 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/11 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/11 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/11 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/11 12:50,4.95,12680.0,France

In [5]:
# o elminar las columnas

no_missing_columns = retail_data.dropna(axis=1)
no_missing_columns

       InvoiceNo StockCode  Quantity    InvoiceDate  UnitPrice         Country
0         536365    85123A         6   12/1/10 8:26       2.55  United Kingdom
1         536365     71053         6   12/1/10 8:26       3.39  United Kingdom
2         536365    84406B         8   12/1/10 8:26       2.75  United Kingdom
3         536365    84029G         6   12/1/10 8:26       3.39  United Kingdom
4         536365    84029E         6   12/1/10 8:26       3.39  United Kingdom
...          ...       ...       ...            ...        ...             ...
541904    581587     22613        12  12/9/11 12:50       0.85          France
541905    581587     22899         6  12/9/11 12:50       2.10          France
541906    581587     23254         4  12/9/11 12:50       4.15          France
541907    581587     23255         4  12/9/11 12:50       4.15          France
541908    581587     22138         3  12/9/11 12:50       4.95          France

[541909 rows x 6 columns]

***Pero borrar filas o columnas no siempre es necesario***

In [9]:
# Puedo llenar los datos faltantes con fillna

retail_data_filled_zeros = retail_data.fillna(0)
missing_retail_data_filled_zeros = retail_data_filled_zeros.isna().sum()
missing_retail_data_filled_zeros

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [16]:
mean_unit_price = retail_data['UnitPrice'].mean()

retail_data_filled_mean = retail_data['UnitPrice'].fillna(mean_unit_price)

In [17]:
retail_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/10 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/10 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/10 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/10 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/10 8:26,3.39,17850.0,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,12/9/11 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,12/9/11 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,12/9/11 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,12/9/11 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,12/9/11 12:50,4.95,12680.0,France